# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 190, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton2.setGeometry(QtCore.QRect(260, 140, 113, 32))
        self.pushButton.setObjectName("pushButton2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 180, 160, 22))
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(20, 220, 160, 22))
        self.horizontalSlider_2.setProperty("value", 68)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 210, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 161, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(170, 230, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(170, 190, 21, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(20, 140, 160, 22))
        self.horizontalSlider_3.setProperty("value", 50)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 16, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(170, 150, 21, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(40, 130, 121, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(50, 30, 91, 81))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("image1.png"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(170, 30, 91, 81))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("image2.png"))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(290, 30, 91, 81))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("image3.png"))
        self.label_12.setObjectName("label_12")
        self.radio_1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radio_1.setGeometry(QtCore.QRect(70, 110, 25, 25))
        self.radio_1.setChecked(True)
        self.radio_2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radio_2.setGeometry(QtCore.QRect(190, 110, 25, 25))
        self.radio_2.setChecked(False)
        self.radio_3 = QtWidgets.QRadioButton(self.centralWidget)
        self.radio_3.setGeometry(QtCore.QRect(310, 110, 25, 25))
        self.radio_3.setChecked(False)
        self.checkbox_seg = QtWidgets.QCheckBox(self.centralWidget)
        self.checkbox_seg.setGeometry(QtCore.QRect(50, 5, 25, 25))
        self.checkbox_seg.setChecked(False)
        self.checkbox_tri = QtWidgets.QCheckBox(self.centralWidget)
        self.checkbox_tri.setGeometry(QtCore.QRect(200, 5, 25, 25))
        self.checkbox_tri.setChecked(True)
        self.checkbox_seg_label = QtWidgets.QLabel(self.centralWidget)
        self.checkbox_seg_label.setGeometry(QtCore.QRect(75, 5, 110, 25))
        self.checkbox_tri_label = QtWidgets.QLabel(self.centralWidget)
        self.checkbox_tri_label.setGeometry(QtCore.QRect(230, 5, 120, 25))



        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
    #    self.statusBar = QtWidgets.QStatusBar(MainWindow)
    #    self.statusBar.setObjectName("statusBar")
    #    MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Write Image"))
        self.pushButton2.setText(_translate("MainWindow", "Take Image"))
        newfont = QtGui.QFont("Helvetica", 6, QtGui.QFont.Bold)
        self.label.setFont(newfont)
        self.label_2.setFont(newfont)
        self.label_9.setFont(newfont)
        self.checkbox_seg_label.setFont(newfont)
        self.checkbox_tri_label.setFont(newfont)
        self.label.setText(_translate("MainWindow", "Transmission Time (seconds)"))
        self.label_2.setText(_translate("MainWindow", "System Lifetime (months)"))
        self.label_3.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "45"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "72"))
        self.label_7.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", '# of beacons'))
        self.checkbox_seg_label.setText(_translate("MainWindow", 'use segmentation'))
        self.checkbox_tri_label.setText(_translate("MainWindow", 'run triangularization'))
